// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shadow.netty.chapter04.generate;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shadow.netty.chapter04.generate.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
