// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shadow.netty.chapter04.generate;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shadow.netty.chapter04.generate.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.shadow.netty.chapter04.generate.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  com.shadow.netty.chapter04.generate.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.shadow.netty.chapter04.generate.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  com.shadow.netty.chapter04.generate.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
