// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shadow.netty.chapter04.generate;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shadow.netty.chapter04.generate.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.shadow.netty.chapter04.generate.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
		  int index);
}
