// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.shadow.netty.chapter04.generate;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_shadow_netty_chapter04_generate_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_shadow_netty_chapter04_generate_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022#com.shadow.netty.chapte" +
      "r04.generate\"%\n\rStreamRequest\022\024\n\014request" +
      "_info\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rrespons" +
      "e_info\030\001 \001(\t\"d\n\023StudentResponseList\022M\n\017s" +
      "tudentResponse\030\001 \003(\01324.com.shadow.netty." +
      "chapter04.generate.StudentResponse\":\n\017St" +
      "udentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005" +
      "\022\014\n\004city\030\003 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030" +
      "\001 \001(\005\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\n" +
      "MyResponse\022\020\n\010realname\030\002 \001(\t2\227\004\n\016Student",
      "Service\022z\n\025GetRealNameByUsername\022..com.s" +
      "hadow.netty.chapter04.generate.MyRequest" +
      "\032/.com.shadow.netty.chapter04.generate.M" +
      "yResponse\"\000\022\200\001\n\017GetStudentByAge\0223.com.sh" +
      "adow.netty.chapter04.generate.StudentReq" +
      "uest\0324.com.shadow.netty.chapter04.genera" +
      "te.StudentResponse\"\0000\001\022\214\001\n\027GetStudentWra" +
      "pperByAges\0223.com.shadow.netty.chapter04." +
      "generate.StudentRequest\0328.com.shadow.net" +
      "ty.chapter04.generate.StudentResponseLis",
      "t\"\000(\001\022w\n\006BiTalk\0222.com.shadow.netty.chapt" +
      "er04.generate.StreamRequest\0323.com.shadow" +
      ".netty.chapter04.generate.StreamResponse" +
      "\"\000(\0010\001B5\n#com.shadow.netty.chapter04.gen" +
      "erateB\014StudentProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_shadow_netty_chapter04_generate_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_shadow_netty_chapter04_generate_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_com_shadow_netty_chapter04_generate_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_shadow_netty_chapter04_generate_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
    internal_static_com_shadow_netty_chapter04_generate_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_shadow_netty_chapter04_generate_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_com_shadow_netty_chapter04_generate_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_shadow_netty_chapter04_generate_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_shadow_netty_chapter04_generate_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_shadow_netty_chapter04_generate_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_shadow_netty_chapter04_generate_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_shadow_netty_chapter04_generate_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_shadow_netty_chapter04_generate_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_shadow_netty_chapter04_generate_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_shadow_netty_chapter04_generate_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
